### ISSUE TITLE
i have problem with OSX 10.11.6

### ISSUE THREAD

**Issue by macgayverarmini** [silicontrip/SkyReader#11]
Hy, when i compile to xcode i have this error 

clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
Undefined symbols for architecture x86_64:
  "Skylander::toyName(unsigned short)", referenced from:
      SkylanderIO::listSkylanders() in fileio.o
      Skylander::getToyTypeName() in skylander.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by silicontrip** [comment]
I found an issue with the Xcode project which didn't include all the needed sources.  I probably used the Makefile to build rather than from within Xcode.

Also fixed some minor warnings.
I've built this from within Xcode without issues.
Let me know if there are any problems.
