### ISSUE TITLE
Completely lost but loving the view

### ISSUE THREAD

**Issue by moregubbinz** [silicontrip/SkyReader#16]
This looks amazing but it's way beyond me at this point, I've got some experience with Java but that's about it.

Is there a step-by-step for noobs on what to download and how to compile everything? Better than that is there a complied version I can sink hours of testing into and report back?

I've downloaded Netbeans and I read that it can be used to compile C++, and I have visual studio 2012 in my download queue. I also have three ports currently at my disposal from various platforms/games and a bunch of figs.

I'll keep plugging away on my own but any and all help will be greatly appreciated :)

**Comment by moregubbinz** [comment]
I've tried a few different forks now and I keep getting the same issue.

Portal Type:
Wii Swap-Force

Typing:
editor -p -o test.bin

Returns:
Reading Skylander

>>> SkylanderIO::initWithPortal
>>> SkylanderIO::ReadPortal
Found portal usb device
>>> PortalIO::Write
<<< PortalIO::Write throw 6
Unable to write to Portal.

Not sure if this is related, but when I tried the Skylanders Editor v2 I noticed that some read/write operations took multiple attempts to go through. I'm going to hook up a PS4 Trap-Team portal when I get home and see if that makes a difference.

Any thoughts?

**Comment by hegyak** [comment]
This issue is related:
https://github.com/silicontrip/SkyReader/issues/12

I haven't been able to figure out what's wrong either.

**Comment by moregubbinz** [comment]
http://www.proxmark.org/forum/viewtopic.php?id=2155&p=3

Most of this stuff is way over my head, but is it possible that the issue is related to timing out? The above link mentions the read/write speeds being artificially slowed. Could that explain my hit and miss experience with the Skylanders Editor V2? Some read/writes got through while others seemed to lag out or get I interrupted.

**Comment by silicontrip** [comment]
I'll have to look further into what is causing the write error.    The only recent portals I have are for the xbox which require a totally different usb communication.  So I can't even reproduce the problem to look into it. 

The proxmark page is talking about a particular brand (i assume proxmark) RFID tag reader to read the skylander toys. It also appears to say that the proxmark is using RS232 as it's comms protocol, which they are trying to emulate over usb. There must also be some type of usb to rs232 hardware in the proxmark reader. 

Could I get a poll of what series portals (and console) you have tried? I'm trying to work out when the communication protocol has changed.

Anyone got a USB sniffer?

**Comment by moregubbinz** [comment]
Tried the following portals:

Xbox 360 Giants - PC detects portal but Skyreader and Skymodder do not
Wii Swapforce - Will read with Skymodder 
PS4 Trapteam - Hit and miss with read/write on Skymodder

Which Windows fork would you recommend trying the above portals with? I'm pretty sure I've tried them all at this point but I'm happy to start from scratch and post the results.

**Comment by moregubbinz** [comment]
Just tried silicontrip/skyreader and here are the results:

Portal:
PS4 Trap-Team.

Sent:
editor -p -o test.bin

Received:
<<<PortalIO::Checkresponse
>>>PortalIO::Write
<<<PortalIO::Write
>>>PortalIO::Checkresponse
PortalIO::Checkresponse hid_read_timeout bytes read 32
<<<

*It then appears to display 3 lines of hex before repeating. Wish I could grab the text from the console but it just keeps running.

Portal:
Wii Swap Force

Sent:
editor -p -o test.bin

Received:
Reading Skylander

>>> SkylanderIO::initWithPortal
>>> SkylanderIO::ReadPortal
Found Portal usb device
>>>PortalIO::Write

Then it hangs.
