### ISSUE TITLE
Swap datas from one skylander to another?

### ISSUE THREAD

**Issue by DTRandom** [silicontrip/SkyReader#21]
I was wondering if there is a method to store infos from one toy, and upload them to another toy (which is'n the same skylander).
**Ex**: save spitfire datas and upload them to stealth elf

I tried to do that by doing:
`editor -p -o spitfire.bin`
with spitfire toy on the portal and then i did:
`editor -i spitfire.bin -P`
with stealth elf toy but i got this error:
`Unknown exception: 22.`

Any ideas?

**Comment by Ph4n70mh4x0r** [comment]
the toys have a thing called a checksum. This makes it so you cant do that.

**Comment by DTRandom** [comment]
Yeah, I was sure they had it, thanks for the answer!

Il Sab 7 Lug 2018, 04:14 Ph4n70mh4x0r <notifications@github.com> ha scritto:
