### ISSUE TITLE
Trying to use this on MacOSX

### ISSUE THREAD

**Issue by EastArctica** [silicontrip/SkyReader#24]
So i have been trying to use this in mac OSX Version 10.11.6 El Capitan But i cant find out how to make the application if anyone can provide me with some info Or the application file. I have XCode installed

Thank you so much in advance!

**Comment by silicontrip** [comment]
using terminal, go into the directory you've downloaded skyreader to and type:
make

You may need to install libusb.  If you are going to be doing any unix level development I highly recommend installing brew: https://brew.sh/

If you do get very stuck I could provide a binary for 10.11
