### ISSUE TITLE
Skylanders portal on Windows 10

### ISSUE THREAD

**Issue by Gruphius** [silicontrip/SkyReader#26]
Hi everybody!
I need some help:
I try to run Skylanders Swap Force on my Windows 10 PC on Cemu. I have already a portal for Wii. When I stick the portal on my PC then I hear the sound, which Windows plays, when you stick an USB on the PC. But cemu says, that there is no portal.
What I have to do, that cemu is detecting the portal? Is there any driver needed?
I have a Wii portal, Skylanders for Wii U, cemu on version 1.11.2 and an Asus PC, R55SL series.
Thx for your help.

**Comment by Gruphius** [comment]
Maybe I have to say, that the Skylanders Swap Force for Wii U is a rom in ISO format.

**Comment by silicontrip** [comment]
Sorry this issue tracker is for SkyReader which is an OSX port of a windows/dos tool.   I know very little about windows 10 or cemu.
