### ISSUE TITLE
Building on windows 

### ISSUE THREAD

**Issue by JanSzumotalski** [silicontrip/SkyReader#29]
How to launch on Windows?

**Comment by silicontrip** [comment]
I'm not in a position to port, build or test a windows binary.

**Comment by JanSzumotalski** [comment]
What should i do then? I have xubuntu in virtual box.

**Comment by silicontrip** [comment]
My build is for OSX.  Although it's portable enough to be built on Linux with minimal changes and some people have forked this repository and made linux specific versions.  I assume that a VM will allow direct access to the usb ports and you'll be able to talk to your portal that way.

**Comment by Dragoonlord82** [comment]
If there is still an interest, i got a Windows 8.1 build.

**Comment by JanSzumotalski** [comment]
@Dragoonlord82 I think it will work on win10. How can I download it?

**Comment by Dragoonlord82** [comment]
Yes it should work with win 10. I have Test it with Xp, Vista, 7 and 8.1
[Skyreader.zip](https://github.com/silicontrip/SkyReader/files/2325172/Skyreader.zip)
Here it is, hope it works for you to.

**Comment by JanSzumotalski** [comment]
Thank you

> This is the moment when the issue should be closed, but someone else has done it before, when it shouldn't be

**Comment by silicontrip** [comment]
Sorry I thought that issues could be raised against forked version. 

I'm hoping that those who do maintain the windows fork read these issues.  I get emailed every issue raised.

Perhaps someone could help out and write build instructions for other platforms.
