### ISSUE TITLE
Build Instructions for Linux

### ISSUE THREAD

**Issue by neilagabriel** [silicontrip/SkyReader#3]
Any build instructions for linux (Ubuntu)? My build fails on some IOKit #includes which seem to be part of an apple/xcode project.

**Comment by silicontrip** [comment]
Try one of the linux forks. https://github.com/reedstrm/SkyReader/

**Comment by neilagabriel** [comment]
Thank you! I was able to build that project without issue. 'editor -p -D' fails with 'Unable to get USB Device List' . I'll investigate that a bit and open a new issue if I can't figure it out.

**Comment by neilagabriel** [comment]
Looks like hid_enumerate is failing. It's not finding any HID devices. The part I don't understand is that according to lsusb, both portals I've tried indicate bDeviceClass=255 (Vendor Specific Class) not 3 (HID Class). They may very well be HID devices but why don't they enumerate that way?

**Comment by neilagabriel** [comment]
Case in point, I plugged in a USB mouse and ran the hidtest provided by the hidapi package and it was recognized. Still doesn't see my portals though.

**Comment by josefwells** [comment]
I have a wii usb portal and linux.  I debugged a bit, while it does see the device, it ends up being unable to write to the portal (which is required to "Restart") the portal.
